### ISSUE TITLE
first example

### ISSUE THREAD

**Issue by biopsin** [0strodamus/CleanLinks2#2]
Heya, was just checking out the first example

 - http://www.foobar.com/track=ftp://gnu.org ➠ ftp://gnu.org/

but what I get instead is -> http://ftp//gnu.org#
version 1.0.2

**Comment by 0strodamus** [comment]
I don't know why that particular example isn't correct, it was just copied from the original extension. I know this isn't a proper solution, but I don't even know if such links actually exist (nor do I care enough to find out) so I removed it from README.md.
