### ISSUE TITLE
"#" sign

### ISSUE THREAD

**Issue by wickedsp1d3r** [0strodamus/CleanLinks2#3]
Hey,

Great extension.
Is there a possibility to make "#" sign's supplement (or the sign itself) behind configuration?
I would like a have cleaned links without this sign.
Thanks.

**Comment by 0strodamus** [comment]
Thanks. I'm sure anything is possible. However, that's the way the original extension worked and if it was a trivial change for me, I would have already made it. If you know what needs to change code-wise to remove the trailing #, you can always submit a pull request or provide a patch.
